# Generated by Django 3.0.8 on 2020-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_info_first_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_info_last_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
