# Generated by Django 3.0.8 on 2020-08-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200819_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_billing_address_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_billing_address_line1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_billing_address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_billing_address_postcode',
        ),
    ]
