# Generated by Django 3.0.8 on 2020-08-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200820_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='personal_info_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='personal_info_last_name',
            new_name='last_name',
        ),
    ]
