# Generated by Django 3.0.8 on 2020-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_type',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
