# Generated by Django 3.0.8 on 2020-07-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_type',
            name='image_url',
        ),
    ]
