# Generated by Django 3.0.8 on 2020-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_training_type_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_type',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
