# Generated by Django 3.0.8 on 2020-08-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200822_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_type',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5),
        ),
    ]
