# Generated by Django 3.0.8 on 2020-07-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_training_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_type',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
