# Generated by Django 3.0.8 on 2020-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_ref', models.CharField(editable=False, max_length=16)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=64)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
