# Generated by Django 3.0.8 on 2020-08-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='user_profile',
            field=models.CharField(max_length=40),
        ),
    ]
