# Generated by Django 3.0.8 on 2020-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200730_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_ref',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
