# Generated by Django 3.0.8 on 2020-08-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200809_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
