# Generated by Django 3.0.8 on 2020-08-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_username'),
        ('checkout', '0005_auto_20200803_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.UserProfile'),
        ),
    ]
